import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const file = path.join(here, '..', 'src', 'styles', 'tokens.css');
const text = readFileSync(file, 'utf8');
const match = text.match(/^\/\* GENERATED FROM silo-marketing\/brand\/tokens\.css\n   source-sha256: ([a-f0-9]{64})\n   Do not edit this file directly\. \*\/\n([\s\S]*)$/);

if (!match) throw new Error('Brand tokens are not a verified generated copy.');
const actual = createHash('sha256').update(match[2]).digest('hex');
if (actual !== match[1]) throw new Error('Generated brand tokens were edited after publication.');

console.log(`Brand tokens verified: ${actual.slice(0, 12)}`);

