import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, '..');
const file = path.join(root, 'src', 'styles', 'tokens.css');
const provenanceFile = path.join(root, 'src', 'assets', 'brand-provenance.json');
const provenance = JSON.parse(readFileSync(provenanceFile, 'utf8'));
const requiredAssets = ['ident-logo.svg', 'logo-cream.svg', 'logo-red.svg'];
const text = readFileSync(file, 'utf8');
const match = text.match(/^\/\* GENERATED FROM silo-marketing\/brand\/tokens\.css\n   source-sha256: ([a-f0-9]{64})\n   Do not edit this file directly\. \*\/\n([\s\S]*)$/);

if (!match) throw new Error('Brand tokens are not a verified generated copy.');
if (provenance.sourceRepository !== 'silo-marketing' || provenance.sourcePath !== 'brand') {
  throw new Error('Brand publication record names an unexpected source.');
}
const actual = createHash('sha256').update(match[2]).digest('hex');
if (actual !== match[1]) throw new Error('Generated brand tokens were edited after publication.');
if (actual !== provenance.tokensSha256) throw new Error('Brand token hash does not match the committed publication record.');

if (!provenance.assets || Object.keys(provenance.assets).sort().join('\n') !== [...requiredAssets].sort().join('\n')) {
  throw new Error('Brand publication record must contain exactly the three canonical assets.');
}
for (const asset of requiredAssets) {
  const expected = provenance.assets[asset];
  const assetFile = path.join(root, 'src', 'assets', asset);
  const assetHash = createHash('sha256').update(readFileSync(assetFile)).digest('hex');
  if (assetHash !== expected) throw new Error(`Generated brand asset was edited after publication: ${asset}`);
}

console.log(`Brand publication record verified: ${actual.slice(0, 12)} + ${requiredAssets.length} assets`);
